version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: playonomics_rabbitmq_broker
    volumes:
      - ./data:/var/lib/rabbitmq/
      - ./logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - playonomics_net

networks:
  hawkerfresh_net:
    driver: bridge
