spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowed-headers: "*"



eureka:
  instance:
    hostname: ${AWS_EUREKA_HOSTNAME}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${AWS_EUREKA_USER}:${AWS_EUREKA_PASSWORD}@${AWS_EUREKA_HOSTNAME}:${AWS_EUREKA_PORT}/eureka



server:
  port: ${AWS_GATEWAY_PORT}
