spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true


eureka:
  instance:
    hostname: eureka.playonomics-dev.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://playonomics:playonomics@eureka.playomonics-dev.com:1111/eureka



server:
  port: 8080
