spring:
  application:
    name: eureka
  security:
    user:
      name: playonomics
      password: playonomics

server:
  port: 1111

eureka:
  instance:
    hostname: eureka.playonomics-dev.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZoneclear: http://eureka.playonomics-dev.com:1111/eureka/