spring:
  application:
    name: eureka
  security:
    user:
      name: ${AWS_EUREKA_USER}
      password: ${AWS_EUREKA_PASSWORD}

server:
  port: ${AWS_EUREKA_PORT}

eureka:
  instance:
    hostname: ${AWS_EUREKA_HOSTNAME}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZoneclear: http://${eureka.instance.hostname}:${server.port}/eureka/