version: "3.8"

services:
  redis:
    image: redis
    command: redis-server --requirepass playonomics
    container_name: playonomics_redis
    volumes:
      - $PWD/data:/var/lib/redis/
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - playonomics_net

networks:
  playonomics_net:
    driver: bridge
